# Numpy - Numeric Python
# scipy - Scientific Python

### similarities between array and list
#### 1. Both are mutable.
#### 2. Borh are used to store the data.
#### 3. Both are indexed.
#### 4. Both are having slicing operation.

### Differnce between array and list.
##             Array--------------------------------------------- List
#####            * it contain only similar datatypes(only num)----------------------------* List can contain any type of data structures.
#####            * we can do mathemtaical operations.-------------------------------------* we can't do the mathematical operations.
#####            * faster than list, less memory.------------------------------------------------- * all are opposite here.

# Array::
 *  its a collection of elements of same type.

# Creating an array.
* create array from list or tupels.

In [1]:
import numpy as np 
help(np.array) # The help fuc helps to understand the syntax and everything.


Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [2]:
#let's create an array()
a = np.array([1,2,3,4]) # one dimensional array.
b = np.array([[1,2,3,4],[1,2,3,4]]) # two dimensional array.[array inside an array] 
c = np.array([1,2,3,4], dtype = 'float') # we can change the dtype using this parameter.
d = np.array((1,2,3,4))# we can use tuple also to creat an array.
e = np.array([[[1,2,3,4],[1,2,3,4]]])# Three dimensional array.[ 2D array within an array] 


# Arange
#### A- array, range 
###### * it will return evenly spaced numerical values with the interval.

In [3]:
# let's create an arange()

a1 = np.arange(1,10) # 10 is exclusive so its take only 9 numbers.
b1 = np.arange(1,10,3)  # 3 is step, it returns step wise.
c1 = np.arange(1,12,dtype = 'float') # we have data type aslo.

# Zeros 
* It creates an arrays filled with zeros.

In [4]:
# let's creata a zeros()

a2 = np.zeros(1,dtype = 'int') # default data type is float.
b2 = np.zeros([2,3], dtype = 'int') # in list we can give the dimensions 2rows 3 columns.

# Ones
* It create an array filled with ones.

In [5]:
# let's create a ones()

a3 = np.ones([3,3], dtype = 'int')

# Linspace
* It creates an array evenly spaced values, it's almost like Arange fun().
###  lin - linear, space


In [6]:
# lets create linear space.

a3 = np.linspace(1,100, num = 5) # evenly spaced is nothing but diffence between all the output's are same.
b3 = np.linspace(1,100, 5, endpoint = False) # if you don't want the ending number, we use this.
c3 = np.linspace(1,100,6,retstep = True)# return step will give you evenly spaced number.
d3 = np.linspace(1,129,3,dtype = 'int')# we use the dtype here also.
d3 = np.linspace(1,35)# if you don't mention num it will return 50 numbers, num default value is 50.

# Eyes
* It return an array with zeros expect the kth value is equal to one.


In [7]:
# let's create an eyes()

a4 = np.eye(2)# if you don't mention column it takes rows as a column.
b4 = np.eye(2,3,k =-1) # the main diagonal is center if you want to change the diagonal we use k, execute differnt numbers and see what's  happening in there.
c4 = np.eye(5,k = 2) # just exceute this
d4 = np.eye(5,5,k = 2, dtype = 'int') # we use the dtype here also.

# Identity 
* It return an square array.

In [8]:
# it create the square array, we need to give only row values.
# same like eye function
e4 = np.identity(5,dtype = 'int')

# Random
* It return an random array
#### In random we have 4 types. 
##### 1. rand ------ unifromally distruibuted values.
##### 2. randn ------- (n) normally distruibuted values.
##### 3.randint -------- uniformally distruibuted integers in a given range.
##### 4.ranf ------------- unifromally distruibuted floating point numbers.

In [9]:
# let's do rand function

a5 = np.random.rand(5,5) # rows and columns it gives random numbers from unifrom distrubution.

In [10]:
# let's do randn 

b5 = np.random.randn(5,5) #it return random values with help standard normal distribution.

In [11]:
# let's do randf

c5 = np.random.ranf(5)# it will give only float numbers with the rows

In [12]:
# let's do randint

d5 = np.random.randint(1,10,size = [5,4])# here end point is exclusive.

# Attributes 

In [13]:
# if you want to check how many dimension in our data we use the ndim array.

e5 = np.ndim(e)
e5

3

In [14]:
# if you want to check the shape of the array use shape()

f5 = np.shape(e)
f5

(1, 2, 4)

In [15]:
# if you want to find the data type of the variable use this.

g5 = e.dtype
g5

dtype('int32')

# Numerical Dtype
* we have five typers 
1. Float.
2. Integer.
3. Complex.
4. Boolean.
5. Unsigned Integer.

In [16]:
# if you want to change the datatype use astype()

a6 = e.astype('float')# it will change the data type to anything you want.

# Indexing ( to retrive a single value we use indexing)
* It's similar to the list indexing.
* 0 based and it has negative indexing also. 
* Same like [list].

In [25]:
# One Dimensional Array.
a7 = np.array([1,2,3,4,5])
a7[4]# postive indexing
a7[-1]# Negative Indexing.


5

In [26]:
# Two Dimensional Array.
b7 = np.array([[1,2],[3,4]])
b7[0,1] #Fist row,second column

2

In [29]:
# Three Dimensional Array.
c7 = np.array([  [[1,2,3],[1,2,3],[1,2,3]],
                [[1,2,3],[1,2,3],[1,2,3]]  ])

In [30]:
c7
# i = which 2d array. 
# j = which row. 
# k = which column.

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [31]:
c7[0][0][2] # i, j, k. 

3

In [32]:
# let's try different.
c7[0,0,2] # working fine.

3

In [33]:
c7[0] # understood!

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

# Slicing(to retrive collection of value we use slicing)


In [34]:
# a[start(inclusive),stop(exclusive), step]



In [35]:
# Slicing One Dimensional

a7

array([1, 2, 3, 4, 5])

In [36]:
a7[0:6]

array([1, 2, 3, 4, 5])

In [37]:
a7[:]

array([1, 2, 3, 4, 5])

In [39]:
a7[:4]

array([1, 2, 3, 4])

In [40]:
a7[::3] # step 

array([1, 4])

In [41]:
a7[1:6:2]

array([2, 4])

In [42]:
# Two Dimesional Slicing.
b7

array([[1, 2],
       [3, 4]])

In [43]:
b7[1:, 1:]

array([[4]])

In [47]:
b7[1:, 0:1] # two dimensional Slicing.

array([[3]])

In [48]:
# Three Dimensional

c7

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [50]:
c7[1,:2, 1:2] # first select the which 2d array you need then all are common.

array([[2],
       [2]])

# Advanced Indexing:
* it's nothing but it will give the copy of the indexed or sliced answer.
* here we index or slicing with index numbers
* We have two types 1) integer indexing. 2) Booleand Indexing.

In [54]:
a8 = np.arange(1,10)
index = np.array([1,3,5])

In [55]:
a8[index] # confusing ! NO, in index I just mentioned index and after that I retriving by orginal array.

array([2, 4, 6])

In [56]:
b8 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [57]:
b8

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
b8[[0,2],[2,0]]

array([3, 7])

In [64]:
b8[[2,0],[0,2]]  #[ choose which row you needed in first box]
                # [ choose which cloumn you needed in second box]

array([7, 3])

In [65]:
b8[[1,2],[2,1]]

array([6, 8])

In [66]:
# Boolean Indexing.

In [67]:
b8[b8>0] # this gives positive values you use negative value as well.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
b8[b8>0] ** 2 # you can perform many operations here. what you need you can do here.

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

#  operations
* for doing operations we need arrays of same size 

In [69]:
a8 * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [70]:
a8 ** 2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [71]:
a8 / 3 # one dimesnion

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667,
       2.        , 2.33333333, 2.66666667, 3.        ])

In [72]:
b8 ** 3 # two dimension , we can do n number of array

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]], dtype=int32)

In [73]:
# we can add two differnt arrays 

In [74]:
a9 = np.array([1,2,3])
b9 = np.array([1,2,3])

In [75]:
a9 + b9

array([2, 4, 6])

In [76]:
a9 * b9

array([1, 4, 9])

In [77]:
# instead of using this we can use this

In [78]:
np.add(a9,b9)

array([2, 4, 6])

In [80]:
np.multiply(a9,b9)

array([1, 4, 9])

# BroadCasting
* It's helps to do operations with different sizes of arrays.

In [83]:
z = np.array([[2],[3],[5]])
y = np.array([1,2,3])

In [84]:
z + y # it satisfied one of the condition.

array([[3, 4, 5],
       [4, 5, 6],
       [6, 7, 8]])

* it has certain rules, both dimension are same.
* otherwise, atleat one data contain 1 dimension.

# Manipulation

### Reshape

In [87]:
# Reshape
np.reshape(a9,(3,1)) #first is array name and second is (rows and columns) 

array([[1],
       [2],
       [3]])

In [90]:
np.reshape(a9,(1,3))

array([[1, 2, 3]])

In [91]:
a9.reshape(1,3) # we can also do like this.

array([[1, 2, 3]])

# resize 
* it will resize the array how much dimension you want and it will repeat the value.

In [95]:
a10 = np.arange(5)

In [97]:
np.resize(a10,(3,3))

array([[0, 1, 2],
       [3, 4, 0],
       [1, 2, 3]])

In [101]:
a10.resize(3,3,refcheck = False)

In [102]:
a10 # we can alos do like this.

array([[0, 1, 2],
       [3, 4, 0],
       [0, 0, 0]])

In [104]:
a10.resize((3,4),refcheck = False)

In [105]:
a10

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

### Flatten
* it helps to flat the array into one dimension. how much the array doesn't matter, it flattens in 1D

In [106]:
a10.flatten()

array([0, 1, 2, 3, 4, 0, 0, 0, 0, 0, 0, 0])

In [107]:
# we have np.transpose
np.transpose(a10) # we can do nd arrays.

array([[0, 4, 0],
       [1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [109]:
a10.T # simple as possible!

array([[0, 4, 0],
       [1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

# Argmax and Argmin
* it gives the index of maximum number and index of minimum numbers.

In [110]:
a10.argmax()

4

In [111]:
a10.argmin()

0

# Replace

In [ ]:
x = np.char.replace(arrayname, 'old', 'new') # it helps to replace the characters.

In [116]:
np.where(a10,4,1) # it helps to replace the numbers

array([[1, 4, 4, 4],
       [4, 1, 1, 1],
       [1, 1, 1, 1]])

# Concatenate

In [118]:
m = np.arange(1,11).reshape(5,2)
n = np.arange(1,11).reshape(5,2)

In [119]:
mn = np.concatenate((m,n), axis = 0)

In [123]:
mn1 = np.concatenate((m,n), axis = 1)

* for concatenate vertically we have np.vstack()
* for concatenate horizontally we have np.hstack()

In [127]:
np.vstack((m,n))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [128]:
np.hstack((m,n))

array([[ 1,  2,  1,  2],
       [ 3,  4,  3,  4],
       [ 5,  6,  5,  6],
       [ 7,  8,  7,  8],
       [ 9, 10,  9, 10]])

# split
* it split the data based on us.

In [129]:
np.split(a10,3) # 3 is nothing but how many arrays i need.

[array([[0, 1, 2, 3]]), array([[4, 0, 0, 0]]), array([[0, 0, 0, 0]])]

* And we have 2 types 
* if you want to split horizontally hsplit()
* if you want to split vertically vsplit()

In [131]:
np.vsplit(a10,3) # nothing but axis = 0

[array([[0, 1, 2, 3]]), array([[4, 0, 0, 0]]), array([[0, 0, 0, 0]])]

In [133]:
np.hsplit(a10,2) # nothing but axis = 1

[array([[0, 1],
        [4, 0],
        [0, 0]]),
 array([[2, 3],
        [0, 0],
        [0, 0]])]

# Insert

In [134]:
last = np.arange(1,20)

In [135]:
np.insert(last,3,34) #last - array name
                     # 3 - you need to tell which index before insert the new value. you need to give index.
                    # 34 - new value

array([ 1,  2,  3, 34,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [136]:

# we can also give multiple index also

np.insert(last,(3,5),80.3) # if you give float it convert into intergers and it give a copy to us.

array([ 1,  2,  3, 80,  4,  5, 80,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19])

# append

In [137]:
np.append(last, 34333) # it will append in last.

array([    1,     2,     3,     4,     5,     6,     7,     8,     9,
          10,    11,    12,    13,    14,    15,    16,    17,    18,
          19, 34333])

 # Delete 

In [143]:
np.delete(last,3) # it will delete we need to give index number to delete those

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

 I THINK I COVERD MOST OF THE TOPIC, THANKS -- ARAVIND.R